"ALTER TABLE users ADD COLUMN has_completed_demography BOOLEAN DEFAULT FALSE;"  
"ALTER TABLE users ADD COLUMN has_seen_explainations BOOLEAN DEFAULT FALSE;"  
"ALTER TABLE users ADD COLUMN age INTEGER;"  
"ALTER TABLE users ADD COLUMN genre VARCHAR(255);"  
"ALTER TABLE users ADD COLUMN etudes VARCHAR(255);"  
"ALTER TABLE users ADD COLUMN classification VARCHAR(255);"  
"ALTER TABLE users ADD COLUMN duree_classification VARCHAR(255);"  
"ALTER TABLE users ADD COLUMN utilisation_ia VARCHAR(255);"  
"ALTER TABLE users ADD COLUMN familiarite_ia INTEGER;" 
